<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GalleryEditor2.aspx.cs" Inherits="Website.GalleryEditor2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
 <script type="text/javascript">
     function editMessage() {
         alert('Item has been edited!');
     }
        </script>
    </head>

    <body>
        <form id="form1" runat="server">
            <div id="editAlbum">
                <asp:GridView ID="grdAlbums" runat="server" AutoGenerateDeleteButton="True" 
                    AutoGenerateColumns="False" DataSourceID="SqlAlbum" DataKeyNames="Album_Id">
                    <Columns>
                        <asp:BoundField DataField="Album_Id" HeaderText="Id" InsertVisible="False" 
                            ReadOnly="True" SortExpression="Id" />
                        
                        <asp:TemplateField HeaderText="Album Name">
                            <ItemTemplate>
                                <asp:Label ID="lblAlbumName" runat="server" 
                                    Text='<%#Eval("Album_Name") %>'>
                                </asp:Label>
                            </ItemTemplate>                            
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="Album Sequence">
                            <ItemTemplate>
                                <asp:Label ID="lblAlbumSeq" runat="server" 
                                    Text='<%#Eval("Album_Sequence") %>'>
                                </asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="Album Description">
                            <ItemTemplate>
                                <asp:Label ID="lblAlbumDesc" runat="server" 
                                    Text='<%#Eval("Album_Description") %>'>
                                </asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
                
                <asp:SqlDataSource ID="SqlAlbum" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:snowdriftersdbConnectionString %>" 
                    SelectCommand="SELECT * FROM [GalleryAlbum_2016]" 
                    DeleteCommand="Delete from [GalleryAlbum_2016] where Album_Id=@Album_Id">
                    <DeleteParameters>
                        <asp:Parameter Name="Album_Id" Type="Int32" />
                    </DeleteParameters>
                </asp:SqlDataSource>

                <br />
                                
                <asp:Label ID="Label1" runat="server" Text="Select Album"></asp:Label>
                &nbsp;  
                
                <asp:DropDownList ID="ddlSelectAlbum1" runat="server" DataSourceID="SqlAlbum" 
                    DataTextField="Album_Name" DataValueField="Album_Id">
                </asp:DropDownList>
                
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label2" runat="server" Text="Enter New Album Name"></asp:Label>
                &nbsp;  
                <asp:TextBox ID="txtAlbumName" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label14" runat="server" Text="Album Sequence"></asp:Label>
                &nbsp;
                <asp:TextBox ID="txtAlbumSeq" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label15" runat="server" Text="Album Description"></asp:Label>
                &nbsp;
                <asp:TextBox ID="txtAlbumDesc" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnSaveAlbum" runat="server" Text="Save Changes" 
                    OnClick="btnSaveAlbum_Click" OnClientClick ="editMessage()" />
            </div>
            
            <br />
            <br />

            <div id="editMedia">
                <asp:GridView ID="grdMedia" runat="server" AutoGenerateDeleteButton="True" 
                    AutoGenerateColumns="False" DataSourceID="SqlMedia" DataKeyNames="Media_Id">
                    <Columns>
                        <asp:BoundField DataField="Media_Id" HeaderText="Id" InsertVisible="False" 
                            ReadOnly="True" SortExpression="Id" />
                        
                        <asp:TemplateField HeaderText="Album">
                            <ItemTemplate>
                                <asp:Label ID="lblAlbumId" runat="server" 
                                    Text='<%#Eval("Album_Id") %>'>
                                </asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="Media Link">
                            <ItemTemplate>
                                <asp:Label ID="lblMediaLink" runat="server" 
                                    Text='<%#Eval("Media_Link") %>'>
                                </asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="File Type">
                            <ItemTemplate>
                                <asp:Label ID="lblFileType" runat="server" 
                                    Text='<%#Eval("File_Type") %>'>
                                </asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Media Sequence">
                            <ItemTemplate>
                                <asp:Label ID="lblMediaSeq" runat="server" 
                                    Text='<%#Eval("Media_Sequence") %>'>
                                </asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="Caption">
                            <ItemTemplate>
                                <asp:Label ID="lblCaption" runat="server" 
                                    Text='<%#Eval("Caption") %>'>
                                </asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Date Uploaded">
                            <ItemTemplate>
                                <asp:Label ID="lblDate" runat="server" 
                                    Text='<%#Eval("Date") %>'>
                                </asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
                
                <asp:SqlDataSource ID="SqlMedia" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:snowdriftersdbConnectionString %>" 
                    SelectCommand="SELECT * FROM [Gallery_2016]" 
                    DeleteCommand="Delete from [Gallery_2016] where Media_Id=@Media_Id">
                    <DeleteParameters>
                        <asp:Parameter Name="Media_Id" Type="Int32" />
                    </DeleteParameters>
                </asp:SqlDataSource>

                <br />
                
                <asp:Label ID="Label3" runat="server" Text="Select Picture"></asp:Label>
                &nbsp;  
                <asp:DropDownList ID="ddlSelectPicture" runat="server" DataSourceID="SqlGetPics" 
                    DataTextField="Media_Link" DataValueField="Media_Id">
                </asp:DropDownList>
                <asp:SqlDataSource ID="SqlGetPics" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:snowdriftersdbConnectionString %>" 
                    SelectCommand="SELECT [Media_Id], [Media_Link] FROM [Gallery_2016] WHERE ([File_Type] = @File_Type)">
                    <SelectParameters>
                        <asp:QueryStringParameter Name="File_Type" QueryStringField="Picture" 
                            Type="String" />
                    </SelectParameters>
                </asp:SqlDataSource>
                &nbsp;&nbsp;&nbsp;
                
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label5" runat="server" Text="Caption"></asp:Label>
                &nbsp;  
                <asp:TextBox ID="txtPicCap" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label6" runat="server" Text="Date"></asp:Label>
                &nbsp;  
                <asp:TextBox ID="txtPicDate" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label7" runat="server" Text="Sequence"></asp:Label>
                &nbsp;
                <asp:TextBox ID="txtPicSequence" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                
                <br />
                
                <asp:Button ID="btnSelectPic" runat="server" Text="Select Picture" 
                    OnClick="btnSelectPic_Click" />
                &nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnSavePic" runat="server" Text="Save Changes" 
                    OnClick="btnSavePic_Click" OnClientClick ="editMessage()" />
            
                <br />
                <br />
            
                <asp:Label ID="Label8" runat="server" Text="Select Video"></asp:Label>
                &nbsp;
                <asp:DropDownList ID="ddlSelectVideo" runat="server" DataSourceID="SqlGetVids" 
                    DataTextField="Media_Link" DataValueField="Media_Id">
                </asp:DropDownList>
                <asp:SqlDataSource ID="SqlGetVids" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:snowdriftersdbConnectionString %>" 
                    SelectCommand="SELECT [Media_Id], [Media_Link] FROM [Gallery_2016] WHERE ([File_Type] = @File_Type)">
                    <SelectParameters>
                        <asp:QueryStringParameter Name="File_Type" QueryStringField="Video" 
                            Type="String" />
                    </SelectParameters>
                </asp:SqlDataSource>
                &nbsp;&nbsp;&nbsp;
                
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label10" runat="server" Text="Caption"></asp:Label>
                &nbsp;
                <asp:TextBox ID="txtVidCap" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label11" runat="server" Text="Date"></asp:Label>
                &nbsp;
                <asp:TextBox ID="txtVidDate" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label12" runat="server" Text="Sequence"></asp:Label>
                &nbsp;
                <asp:TextBox ID="txtVidSequence" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label13" runat="server" Text="Enter URL"></asp:Label>
                &nbsp;
                <asp:TextBox ID="txtURL" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnInsertVid" runat="server" Text="Insert Video" />
                &nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnSaveVid" runat="server" Text="Save Changes" 
                    OnClick="btnSaveVid_Click" OnClientClick ="editMessage()"/>
            </div>

            <br />
            <br />
            <asp:Button ID="btnBack" runat="server" OnClick="btnBack_Click" Text="Back" />
        </form>
    </body>
</html>
