<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SponserEditor.aspx.cs" Inherits="Website.SponserEditor" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<link rel="icon" 
      type="image/png" 
      href="favicon.ico">
<head id="Head1" runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 206px;
        }
    </style>
</head>
    <script runat="server">
  void Page_Load(object sender, EventArgs e)
  {
    
    if (Session["status"] == null || !(Session["status"].ToString().Equals("valid")))
        Response.Redirect("ownerlogin.aspx");
  }

  void Signout_Click(object sender, EventArgs e)
  {
      FormsAuthentication.SignOut();
      Session["status"] = "";
      //FormsAuthentication.RedirectFromLoginPage

      //(Username.Text, Persist.Checked);
      Response.Redirect("ownerlogin.aspx")
          ;
  }
</script>
<body>
    <form id="form1" runat="server">
    <div>
        <div>
        <body style="background-color:lightgrey">
        <div id="header" class="container">
	<div id="logo" class="container">
		<h2><a href="HomePage.aspx" class="image-full"><img src="images/MJSNOWGUY.png" /></a>
        <h2>Welcome to the Content Manager for the Sponsors.</h2>
        
            &nbsp;<a href="EventEditor.aspx">Events Editor</a> | <a href="Gallery_Editor1.aspx">Gallery Editor</a> 
    | <a href="SponserEditor.aspx">Sponsors Editor</a>&nbsp; | <a href="FacebookOwner.aspx">Facebook / Twitter Editor</a><br /> <br /><br />
        
	</div>

        <asp:Panel ID="Panel1" runat="server" GroupingText="Sponsor Editor">
            
            <table>
            
                <tr>
                    <td class="auto-style1">Name:<br /><asp:TextBox ID="txtName" runat="server"></asp:TextBox></td>
                    
                    <td>Phone:<br /><asp:TextBox ID="txtPhone"  runat="server"></asp:TextBox></td>
                   
                </tr>
                <tr><td>
                       Address:<br /><asp:TextBox ID="txtAddress" runat="server" TextMode="MultiLine" Width="265px" Height="50px"></asp:TextBox>
                    </td></tr>
                <tr>                     
                    <td colspan="2">Short Description:<br /><asp:TextBox ID="txtShortDescription" runat="server" TextMode="MultiLine" Width="265px" Height="50px"></asp:TextBox></td>
                                     
                </tr>
                <tr><td class="auto-style1">Email:<br /><asp:TextBox ID="txtEmail" runat="server"></asp:TextBox></td>
                    <td>Logo:<br /><asp:FileUpload ID="fupLogo" runat="server" /></td>
                </tr>
                <tr>
            
                    <td colspan="2">Website:<br /><asp:TextBox ID="txtWebsite" runat="server" ></asp:TextBox></td>
               </tr>
                        <tr><td><asp:Button ID="btnInsert" runat="server" Text="Add Sponsor" Width="142px" OnClick="btnInsert_Click" /></td>
                </tr>
                
            </table>
      
        </asp:Panel>
    
    </div>
        <p>
            &nbsp;</p>
        <p>
            All Sponsors</p>
        <p>
            <asp:GridView ID="grdSponsor" runat="server" DataKeyNames="sponsorid" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowCancelingEdit="grdSponsor_RowCancelingEdit" OnRowDeleting="grdSponsor_RowDeleting" OnRowEditing="grdSponsor_RowEditing" OnRowUpdating="grdSponsor_RowUpdating" >
            </asp:GridView>
        </p>
            <p>
        <asp:Button ID="Submit1" OnClick="Signout_Click" 
       Text="Sign Out" runat="server" />
        </p>
        
    </form>
</body>
</html>